// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clientExistsByAccessKey = `-- name: ClientExistsByAccessKey :one
SELECT EXISTS(SELECT 1 FROM clients WHERE access_key = ?) AS client_exists
`

func (q *Queries) ClientExistsByAccessKey(ctx context.Context, accessKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, clientExistsByAccessKey, accessKey)
	var client_exists int64
	err := row.Scan(&client_exists)
	return client_exists, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, name, access_key, secret_key, role)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, access_key, secret_key, role, is_active, created_at, updated_at
`

type CreateClientParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	AccessKey string `json:"access_key"`
	SecretKey string `json:"secret_key"`
	Role      string `json:"role"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.AccessKey,
		arg.SecretKey,
		arg.Role,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKey,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = ?
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByAccessKey = `-- name: GetClientByAccessKey :one
SELECT id, name, access_key, secret_key, role, is_active, created_at, updated_at
FROM clients WHERE access_key = ?
`

func (q *Queries) GetClientByAccessKey(ctx context.Context, accessKey string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByAccessKey, accessKey)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKey,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, access_key, secret_key, role, is_active, created_at, updated_at
FROM clients WHERE id = ?
`

func (q *Queries) GetClientByID(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKey,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, access_key, role, is_active, created_at, updated_at
FROM clients ORDER BY created_at DESC
`

type ListClientsRow struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	AccessKey string       `json:"access_key"`
	Role      string       `json:"role"`
	IsActive  int64        `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessKey,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = ?, role = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, access_key, secret_key, role, is_active, created_at, updated_at
`

type UpdateClientParams struct {
	Name     string `json:"name"`
	Role     string `json:"role"`
	IsActive int64  `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKey,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClientSecret = `-- name: UpdateClientSecret :execrows
UPDATE clients SET secret_key = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateClientSecretParams struct {
	SecretKey string `json:"secret_key"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClientSecret, arg.SecretKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
