// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migrations.sql

package sqlc

import (
	"context"
)

const getAppliedMigrations = `-- name: GetAppliedMigrations :many
SELECT version, applied_at FROM schema_migrations ORDER BY version
`

func (q *Queries) GetAppliedMigrations(ctx context.Context) ([]SchemaMigration, error) {
	rows, err := q.db.QueryContext(ctx, getAppliedMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaMigration{}
	for rows.Next() {
		var i SchemaMigration
		if err := rows.Scan(&i.Version, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMigration = `-- name: InsertMigration :exec
INSERT INTO schema_migrations (version) VALUES (?)
`

func (q *Queries) InsertMigration(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, insertMigration, version)
	return err
}
