// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type SchemaMigration struct {
	Version   int64        `json:"version"`
	AppliedAt sql.NullTime `json:"applied_at"`
}
